[package]
name = "nettverksprogrammering"
version = "0.1.0"
authors = ["mokkalokka <michael.larsen90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_input = "0.8.3"
rand = "0.7"



